let subjectsArr = [
   "MacOs", 
    "File Tree", 
    "File extension", 
    "HTML", 
    "CSS",
    "Advanced CSS", 
    "JavaScript", 
    "Web APIs", 
    "Third Party APIs", 
    "Server Side APIs", 
    "NodeJS", 
    "OOP",
    "Express", 
    "MySQL", 
    "ORM", 
    "MVC", 
    "NoSQL", 
    "PWA", 
    "ReactJS", 
    "MERN", 
    // "Algorithms", 
    // "Computer Science",  
    // "Version Control .git", 
    // "GitLab, Github", 
    // "Agile", 
    // "Handlebars",
    // "MongoDB", 
    // "Heroku",
    // "mongoose", 
    // "Sequelize", 
    // "Cookies", 
    // "the DOM", 
    // "HTTP Protocol", 
    // "HTTP methods", 
    // "Request-Response Cycle", 
    // "Routing", 
    // "RE-ROUTING", 
    // "ERR Codes",
    // "Command Line", 
    // "Command Line Interface", 
    // "Command Line App",
    // "Semantic Elements", 
    // "Repo", 
    // "Pull Request", 
    // "How do I git merge again?", 
    // "Best Practices", 
    // "Refractoring", 
    // "CSS Reset", 
    // "Cross-Browser Compatibility",
    // "Environment", 
    // "Environmental Variables", 
    // "Markdown....Markup...README", 
    // "Responsive Design", 
    // "Mobile-First",
    // "Wireframe", 
    // "Cloud Services", 
    // "Google Drive, Docs, Anything- they have it", 
    // "YouTube", 
    // "Merge Conflict", 
    // "My what branch does what with what branch?",
    // "Arrays, Objects, Literals...", 
    // "Prototype Inheritance", 
    // "Constructor",
    // "it's all functions", 
    // "Scope", 
]; 